# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.codezeg.com
date_format: "ordinal"
title: CodeZeg
subtitle: "欢迎来到 召唤师峡谷"
description: "李纠结的个人博客"
keywords: 李纠结, CodeZeg, 张二狗, 李思禹, 花千骨, Unity, 游戏开发
favicon: /favicon.ico
timezone: Asia/Chengdu
encoding: "utf-8"
source_code: https://github.com/codezeg

# ---------------- #
#      Author      #
# ---------------- #
author: siyu li
organization: 1ktower
organization_url: http://www.1ktower.com/
location: Chengdu, China
email: 576603306@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 思考

  -
    href: /wiki/
    label: 学习
 
 # -
 #   href: /practice/
 #   label: 实践
    
  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
#     - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: codezeg
# douban_username: codezeg
# facebook_username: codezeg
# weibo_username: codezeg
# zhihu_username: codezeg
# twitter_username: codezeg

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: codezeg
# disqus_username: codezeg

# ---------------- #
#      Share       #
# ---------------- #
share: false

# ---------------- #
#    analytics     #
# ---------------- #
ba_track_id: bd2467324f743720cbfae5e109983a92

# ---------------- #
#      Repos       #
# ---------------- #
popular_repos: ['codezeg.github.io', 'lol_rpg']
contribute_repos: ['UnrealEngine', 'EpicGames/UnrealEngine']
